apiVersion: v1
kind: Pod
metadata:
  name: openshift-kie-jdkhttp
spec:
  containers:
    - name: main
      image: "<user>/openshift-kie-jdkhttp:<tag>"
      env:
        - name: JAVA_TOOL_OPTIONS
          value: -agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n
                -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=3000
                -Dcom.sun.management.jmxremote.rmi.port=3001 -Djava.rmi.server.hostname=127.0.0.1
                -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName