apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openshift-kie-jdkhttp
    version: v1
  name: openshift-kie-jdkhttp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openshift-kie-jdkhttp
      version: v1
  template:
    metadata:
      labels:
        app: openshift-kie-jdkhttp
        version: v1
    spec:
      serviceAccountName: openshift-kie-jdkhttp
      securityContext:
        runAsUser: <id_user>
        runAsNonRoot: true
      containers:
        - env:
          name: openshift-kie-jdkhttp
          image: <user>/openshift-kie-jdkhttp:<tag>
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 1
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
          securityContext:
            privileged: false