package org.drools.cep

import org.kie.hacep.model.StockTickEvent
import org.kie.hacep.consumer.DroolsExecutor
import java.util.UUID

rule StockAverage when
  $name : String()
  accumulate ( StockTickEvent( company == $name, $p : price ) over window:time(30s), $avg : average( $p ) )
then
  System.out.println("Average price for " + $name + " is " + $avg);
end

rule StockLog when
  $stock:StockTickEvent()
then
    DroolsExecutor.getInstance().execute( () -> {
        String id = UUID.randomUUID().toString();
        System.out.println("Price for " + $stock.getCompany() + " is " + $stock.getPrice() + " id:" + id);
        return id;
    });
end
